
version: '3.3'

services:
  jenkins:
    build:
      context: .
    ports:
     - 8081:8080
     - 50000:50000
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/usr/local/conf.yml
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  registry:
    image: registry:2
    restart: always
    container_name: registry
    ports:
      - 5000:5000
    volumes:
      - ./registry:/var/lib/registry
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
