jenkins:
  systemMessage: "Welcome to WanderAR"
  remotingSecurity:
    enabled: true

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          name: Admin
          password: ${JENKINS_ADMIN_PASSWORD}

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Marvin master"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"

jobs:
  - file: /usr/local/job_dsl.groovy
