name: Test and push to main

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    
  workflow_dispatch:
  
jobs:
  push_to_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push to main
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: main
          FOLDER: ./
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}